language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3.24
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "yoOlkO87bNGEA/LYMbTJ53AAK+1pxIlgWvaPMvLdDWbGfGxUDU2052U//sM1dQ/2vCpJ2PVm5ol7ZztYbc2+lf0YeKIVk5T4XrNqeAJUpQBwAXtBR9T9XAx1jtC2zUEkEK3HtRTb/ss12TtKkGK0AldtSj14zJrEVtSpYsr/nqsLZtCY8x4ShFd1YgI24wiiQxa/essP+nkK8DxZTRTF/ZNMUslYBgXY32kW5MAWmVhTJER3OKCId9VJUqGlZJHRu25FG2HtwB+NrN1i3frjn8oHkO5xUL6XPbBlFSaT/AyhhsDWfPbY8b/rcauplGWMYWA1pFPxaxYXIgCaBLebLuMKk7VpUK4e46kKF5aKtZZ+fplhJ3U0o3jbewp3NlUCmx4qIacMqhkLEQiD+59ugoXfKzHYa5fhm85gKw1v4JBqjtVztyDMBT2C7dXj8eu/bnx1o3kjMjCbB0ersrsAotxgcSMXQB0EQhBQFOEXsJ8jLhnbfCpQSQxt51vnuzylTkanFryIrUkeA4MewiLfy0J3e9gfuSSMcCYavmqipez4Em13xVv8iWjcJPDJeMQVDCIYoXcOW6MoRjcv1g0Uj2AdArrtjUPqH9cqNHpSTqk/LqrtsZT/GDkVWV1FZ0++kEas24GmYWD+x5ESduuS6Ymz9z5upBvxT4wkE4tCvqc="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
